plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme

remote_theme: jekyll/minima

#theme: minima
locale: "en-US"
title: FMarslan
author:
  name: Fatih Mehmet ARSLAN
  email: contact@fmarslan.com
  
description: >
  I'm a software engineer.  
  I'm giving consulting about software architect and I'm  a freelance software development

show_excerpts: true

header_pages:
  - mailto:contact@fmarslan.com

pages:
  - Contact

 
minima:
  skin: solarized-dark
  date_format: "%b %-d, %Y"
  social_links:
    twitter: FMArslan46
    github: fmarslan
    linkedin: fmarslan
