plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme

remote_theme: jekyll/minima

#theme: minima
locale: "en-US"
title: FMArslan
author:
  name: Fatih Mehmet ARSLAN
  email: contact@fmarslan.com
  
description: >
  I'm a software engineer.  
  I'm giving consulting about software architect and I'm  a freelance software development

show_excerpts: true
 
minima:
  date_format: "%b %-d, %Y"
  social_links:
    twitter: FMArslan46
    github: fmarslan
    linkedin: fmarslan
