markdown: kramdown
theme: minima
locale                   : "en-US"
title                    : "Fatih Mehmet ARSLAN"
title_separator          : "-"
name                     : &name "FMArslan"
description              : &description "Fatih Mehmet ARSLAN"
