markdown: kramdown
remote_theme: koirand/pulp
#theme: jekyll-theme-tactile
locale                   : "en-US"
title                    : "Fatih Mehmet ARSLAN - FMArslan"
title_separator          : "-"
name                     : &name "FMArslan"
description              : &description "Fatih Mehmet ARSLAN"
