plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme

remote_theme: jekyll/minima

#theme: minima
locale: "en-US"
title: FMarslan
author:
  name: Fatih Mehmet ARSLAN
  email: contact@fmarslan.com
description: >
  Software Architect Project Lead


show_excerpts: true

header_pages:
 - 
 
minima:
  skin: solarized-dark
  date_format: "%b %-d, %Y"
  social_links:
    twitter: FMArslan46
    github: fmarslan
    linkedin: fmarslan
