markdown: kramdown
theme: minima
locale: "en-US"
title: FMarslan
author:
  name: Fatih Mehmet ARSLAN
  email: contact@fmarslan.com
description: > # this means to ignore newlines until "show_excerpts:"
  I started an educational life with a technical high school - computer programming department. 
  After that, I completed my undergraduate studies at Gazi University and Karabuk University. 
  I have 9+ years of professional experience as a Software Architect with Java and C#. 
  I have experience at NoSQL, RDBMS, Javascript, Bigdata, CI Tools, Kubernetes, Cloud Programming, and various other technologies required by projects I worked on. 
  Through all my professional experience, I have worked hard to improve myself. My previous job experiences are listed on my profile.

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
minima:
  date_format: "%b %-d, %Y"
  # generate social links in footer
  social_links:
    twitter: FMArslan46
    github: fmarslan
    linkedin: fmarslan
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com
