plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme

remote_theme: jekyll/minima

#theme: minima
locale: "en-US"
title: FMarslan
author:
  name: Fatih Mehmet ARSLAN
  email: contact@fmarslan.com
description: >
  I started an educational life with a technical high school - computer programming department. 
  After that, I completed my undergraduate studies at Gazi University and Karabuk University. 
  I have 9+ years of professional experience as a Software Architect with Java and C#. 
  I have experience at NoSQL, RDBMS, Javascript, Bigdata, CI Tools, Kubernetes, Cloud Programming, and various other technologies required by projects I worked on. 
  Through all my professional experience, I have worked hard to improve myself. My previous job experiences are listed on my Linkedin profile.


header_pages:
# - contact.md
 
minima:
  skin: solarized-dark
  date_format: "%b %-d, %Y"
  social_links:
    twitter: FMArslan46
    github: fmarslan
    linkedin: fmarslan
